### PR TITLE
fix: use script to load fonts

### LINKED ISSUE #20: Font flickers when changing page
This bug has been introduced in version 1.1.0, here's a codesandbox link:
https://codesandbox.io/s/confident-rgb-sj4lm?file=/pages/about.vue

When navigating between pages, the font gets unavailable for some milliseconds.

Thanks!

EDIT: Open chrome inspector to make it more noticeable

### LINKED ISSUE #24: Option to not use onload,  vmid: 'google-fonts',  media: 'print', onload and vmid on AMP pages is not supported
There's how to disable 
`     vmid: 'google-fonts',
      media: 'print',
      onload: 'this.onload=null;this.removeAttribute(\'media\');'
 `
to use this module on AMP pages

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Fix import google fonts css
https://stackoverflow.com/questions/25230264/how-to-keep-css-from-render-blocking-my-website

Resolve #24 
Resolve #20

### CODE REVIEW

**Comment by ivodolenc** [comment]
> Load google fonts using style import
> https://stackoverflow.com/questions/25230264/how-to-keep-css-from-render-blocking-my-website
> 
> Resolve #24
> Resolve #20

This works in a `dev` and `prod` mode without flickering 👍 But according to [#538](https://github.com/nuxt/vue-meta/issues/538), is it safe to use the `once: true` attribute in production?

**Comment by ricardogobbosouza** [comment]
@ivodolenc thanks,
I will remove.

**Comment by ivodolenc** [comment]
@ricardogobbosouza thanks for reply. Just one more thing, is `preload` (if true) effective when styles are imported that way (inside the body)? I get a warning from the console log (... was preloaded using link preload but not used within a few seconds ...). When I remove the `preload` tag, the warning disappears. But other than that, it works well without flickering.

**Comment by ricardogobbosouza** [comment]
@ivodolenc could test this latest update?

**Comment by ivodolenc** [comment]
> @ivodolenc could test this latest update?

@ricardogobbosouza Seems good to me. Works as expected in `dev` & `prod` mode 👍

**Review by Atinux — APPROVED** [review]

**Pull request merged**
