### PR TITLE
fix: font flickers when changing page

### LINKED ISSUE #20: Font flickers when changing page
This bug has been introduced in version 1.1.0, here's a codesandbox link:
https://codesandbox.io/s/confident-rgb-sj4lm?file=/pages/about.vue

When navigating between pages, the font gets unavailable for some milliseconds.

Thanks!

EDIT: Open chrome inspector to make it more noticeable

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #20 

Disable reactivity on link
https://vue-meta.nuxtjs.org/api/#once

### CODE REVIEW

**Comment by Atinux** [comment]
I think we should also implement font-display like @pi0 commented on https://github.com/nuxt-community/google-fonts-module/issues/22

**Comment by bissolli** [comment]
Guys any guess on when this PR will be merged? I am thinking of using this module instead of the one I have in place but I can't do that before the flicker is fixed!

Great module by the way =)

**Comment by ricardogobbosouza** [comment]
> I think we should also implement font-display like @pi0 commented on #22

@Atinux better to create in another PR, no?

**Comment by ricardogobbosouza** [comment]
> Guys any guess on when this PR will be merged? I am thinking of using this module instead of the one I have in place but I can't do that before the flicker is fixed!
> 
> Great module by the way =)

@bissolli awaiting review..

**Comment by ricardogobbosouza** [comment]
@bissolli need analyze, it seems not to be working in production
https://github.com/nuxt-community/google-fonts-module/issues/20#issuecomment-710678864

**Comment by Atinux** [comment]
Merging as a hot fix now and releasing to at least fix the flicker.

But I am not happy about having this: https://github.com/nuxt-community/google-fonts-module/blob/master/lib/module.js#L80-L82

And I believe we should work on v1.2 including #22 :)

**Comment by ricardogobbosouza** [comment]
@Atinux I agree

**Pull request merged**
